// Code generated by pigeon; DO NOT EDIT.

package dash

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"log"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Dash",
			pos:  position{line: 5, col: 1, offset: 19},
			expr: &actionExpr{
				pos: position{line: 5, col: 9, offset: 27},
				run: (*parser).callonDash1,
				expr: &seqExpr{
					pos: position{line: 5, col: 9, offset: 27},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 5, col: 9, offset: 27},
							label: "es",
							expr: &zeroOrMoreExpr{
								pos: position{line: 5, col: 12, offset: 30},
								expr: &actionExpr{
									pos: position{line: 5, col: 13, offset: 31},
									run: (*parser).callonDash5,
									expr: &seqExpr{
										pos: position{line: 5, col: 13, offset: 31},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 5, col: 13, offset: 31},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 5, col: 15, offset: 33},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 5, col: 17, offset: 35},
													name: "Expr",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 5, col: 22, offset: 40},
												name: "_",
											},
											&zeroOrOneExpr{
												pos: position{line: 5, col: 24, offset: 42},
												expr: &ruleRefExpr{
													pos:  position{line: 5, col: 24, offset: 42},
													name: "CommaToken",
												},
											},
										},
									},
								},
							},
						},
						&notExpr{
							pos: position{line: 5, col: 56, offset: 74},
							expr: &anyMatcher{
								line: 5, col: 57, offset: 75,
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Expr",
			pos:  position{line: 11, col: 1, offset: 171},
			expr: &choiceExpr{
				pos: position{line: 11, col: 9, offset: 179},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 11, col: 9, offset: 179},
						name: "Class",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 17, offset: 187},
						name: "Slot",
					},
					&ruleRefExpr{
						pos:  position{line: 11, col: 24, offset: 194},
						name: "Form",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Form",
			pos:  position{line: 13, col: 1, offset: 200},
			expr: &choiceExpr{
				pos: position{line: 13, col: 9, offset: 208},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 13, col: 9, offset: 208},
						name: "Infix",
					},
					&ruleRefExpr{
						pos:  position{line: 13, col: 17, offset: 216},
						name: "Term",
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "Term",
			pos:  position{line: 15, col: 1, offset: 222},
			expr: &choiceExpr{
				pos: position{line: 15, col: 9, offset: 230},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 15, col: 9, offset: 230},
						name: "Select",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 18, offset: 239},
						name: "FunCall",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 28, offset: 249},
						name: "List",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 35, offset: 256},
						name: "Literal",
					},
					&ruleRefExpr{
						pos:  position{line: 15, col: 45, offset: 266},
						name: "Symbol",
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "Class",
			pos:  position{line: 17, col: 1, offset: 274},
			expr: &actionExpr{
				pos: position{line: 17, col: 10, offset: 283},
				run: (*parser).callonClass1,
				expr: &seqExpr{
					pos: position{line: 17, col: 10, offset: 283},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 17, col: 10, offset: 283},
							name: "ClsToken",
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 19, offset: 292},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 21, offset: 294},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 26, offset: 299},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 17, col: 29, offset: 302},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 17, col: 31, offset: 304},
							label: "block",
							expr: &ruleRefExpr{
								pos:  position{line: 17, col: 37, offset: 310},
								name: "Block",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ClsToken",
			pos:  position{line: 24, col: 1, offset: 444},
			expr: &litMatcher{
				pos:        position{line: 24, col: 13, offset: 456},
				val:        "cls",
				ignoreCase: false,
				want:       "\"cls\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Slot",
			pos:  position{line: 26, col: 1, offset: 463},
			expr: &choiceExpr{
				pos: position{line: 26, col: 9, offset: 471},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 26, col: 9, offset: 471},
						name: "TypeAndArgsAndBlockSlot",
					},
					&ruleRefExpr{
						pos:  position{line: 27, col: 9, offset: 540},
						name: "TypeAndBlockSlot",
					},
					&ruleRefExpr{
						pos:  position{line: 28, col: 9, offset: 674},
						name: "TypeAndValueSlot",
					},
					&ruleRefExpr{
						pos:  position{line: 29, col: 9, offset: 813},
						name: "ValueOnlySlot",
					},
					&ruleRefExpr{
						pos:  position{line: 30, col: 9, offset: 907},
						name: "TypeOnlySlot",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "TypeAndValueSlot",
			pos:  position{line: 32, col: 1, offset: 995},
			expr: &actionExpr{
				pos: position{line: 32, col: 21, offset: 1015},
				run: (*parser).callonTypeAndValueSlot1,
				expr: &seqExpr{
					pos: position{line: 32, col: 21, offset: 1015},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 32, col: 21, offset: 1015},
							label: "vis",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 25, offset: 1019},
								name: "Visibility",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 36, offset: 1030},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 38, offset: 1032},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 43, offset: 1037},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 46, offset: 1040},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 48, offset: 1042},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 59, offset: 1053},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 61, offset: 1055},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 67, offset: 1061},
								name: "Type",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 72, offset: 1066},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 32, col: 74, offset: 1068},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 32, col: 78, offset: 1072},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 32, col: 80, offset: 1074},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 32, col: 86, offset: 1080},
								name: "Form",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ValueOnlySlot",
			pos:  position{line: 41, col: 1, offset: 1232},
			expr: &actionExpr{
				pos: position{line: 41, col: 18, offset: 1249},
				run: (*parser).callonValueOnlySlot1,
				expr: &seqExpr{
					pos: position{line: 41, col: 18, offset: 1249},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 41, col: 18, offset: 1249},
							label: "vis",
							expr: &ruleRefExpr{
								pos:  position{line: 41, col: 22, offset: 1253},
								name: "Visibility",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 41, col: 33, offset: 1264},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 41, col: 35, offset: 1266},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 41, col: 40, offset: 1271},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 41, col: 43, offset: 1274},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 41, col: 45, offset: 1276},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 41, col: 49, offset: 1280},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 41, col: 51, offset: 1282},
							label: "val",
							expr: &ruleRefExpr{
								pos:  position{line: 41, col: 55, offset: 1286},
								name: "Form",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "TypeOnlySlot",
			pos:  position{line: 49, col: 1, offset: 1407},
			expr: &actionExpr{
				pos: position{line: 49, col: 17, offset: 1423},
				run: (*parser).callonTypeOnlySlot1,
				expr: &seqExpr{
					pos: position{line: 49, col: 17, offset: 1423},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 49, col: 17, offset: 1423},
							label: "vis",
							expr: &ruleRefExpr{
								pos:  position{line: 49, col: 21, offset: 1427},
								name: "Visibility",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 49, col: 32, offset: 1438},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 49, col: 34, offset: 1440},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 49, col: 39, offset: 1445},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 49, col: 42, offset: 1448},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 49, col: 44, offset: 1450},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 49, col: 55, offset: 1461},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 49, col: 57, offset: 1463},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 49, col: 63, offset: 1469},
								name: "Type",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "TypeAndBlockSlot",
			pos:  position{line: 57, col: 1, offset: 1596},
			expr: &actionExpr{
				pos: position{line: 57, col: 21, offset: 1616},
				run: (*parser).callonTypeAndBlockSlot1,
				expr: &seqExpr{
					pos: position{line: 57, col: 21, offset: 1616},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 57, col: 21, offset: 1616},
							label: "vis",
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 25, offset: 1620},
								name: "Visibility",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 36, offset: 1631},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 57, col: 38, offset: 1633},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 43, offset: 1638},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 46, offset: 1641},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 48, offset: 1643},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 59, offset: 1654},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 57, col: 61, offset: 1656},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 67, offset: 1662},
								name: "Type",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 72, offset: 1667},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 57, col: 74, offset: 1669},
							label: "block",
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 80, offset: 1675},
								name: "Block",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "TypeAndArgsAndBlockSlot",
			pos:  position{line: 70, col: 1, offset: 1932},
			expr: &actionExpr{
				pos: position{line: 70, col: 28, offset: 1959},
				run: (*parser).callonTypeAndArgsAndBlockSlot1,
				expr: &seqExpr{
					pos: position{line: 70, col: 28, offset: 1959},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 70, col: 28, offset: 1959},
							label: "vis",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 32, offset: 1963},
								name: "Visibility",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 43, offset: 1974},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 70, col: 45, offset: 1976},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 50, offset: 1981},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 53, offset: 1984},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 70, col: 55, offset: 1986},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 60, offset: 1991},
								name: "ArgTypes",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 69, offset: 2000},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 71, offset: 2002},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 82, offset: 2013},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 70, col: 84, offset: 2015},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 90, offset: 2021},
								name: "Type",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 70, col: 95, offset: 2026},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 70, col: 97, offset: 2028},
							label: "block",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 103, offset: 2034},
								name: "Block",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Visibility",
			pos:  position{line: 84, col: 1, offset: 2336},
			expr: &choiceExpr{
				pos: position{line: 84, col: 15, offset: 2350},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 84, col: 15, offset: 2350},
						run: (*parser).callonVisibility2,
						expr: &ruleRefExpr{
							pos:  position{line: 84, col: 15, offset: 2350},
							name: "PubToken",
						},
					},
					&actionExpr{
						pos: position{line: 85, col: 15, offset: 2406},
						run: (*parser).callonVisibility4,
						expr: &ruleRefExpr{
							pos:  position{line: 85, col: 15, offset: 2406},
							name: "PvtToken",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "PubToken",
			pos:  position{line: 86, col: 1, offset: 2449},
			expr: &litMatcher{
				pos:        position{line: 86, col: 13, offset: 2461},
				val:        "pub",
				ignoreCase: false,
				want:       "\"pub\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "PvtToken",
			pos:  position{line: 87, col: 1, offset: 2467},
			expr: &litMatcher{
				pos:        position{line: 87, col: 13, offset: 2479},
				val:        "pvt",
				ignoreCase: false,
				want:       "\"pvt\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Id",
			pos:  position{line: 89, col: 1, offset: 2486},
			expr: &ruleRefExpr{
				pos:  position{line: 89, col: 7, offset: 2492},
				name: "WordToken",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "WordToken",
			pos:  position{line: 90, col: 1, offset: 2502},
			expr: &actionExpr{
				pos: position{line: 90, col: 14, offset: 2515},
				run: (*parser).callonWordToken1,
				expr: &oneOrMoreExpr{
					pos: position{line: 90, col: 14, offset: 2515},
					expr: &charClassMatcher{
						pos:        position{line: 90, col: 14, offset: 2515},
						val:        "[a-zA-Z0-9]",
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "UpperId",
			pos:  position{line: 93, col: 1, offset: 2561},
			expr: &ruleRefExpr{
				pos:  position{line: 93, col: 12, offset: 2572},
				name: "UpperToken",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "UpperToken",
			pos:  position{line: 94, col: 1, offset: 2583},
			expr: &actionExpr{
				pos: position{line: 94, col: 15, offset: 2597},
				run: (*parser).callonUpperToken1,
				expr: &seqExpr{
					pos: position{line: 94, col: 15, offset: 2597},
					exprs: []any{
						&charClassMatcher{
							pos:        position{line: 94, col: 15, offset: 2597},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
						&zeroOrMoreExpr{
							pos: position{line: 94, col: 20, offset: 2602},
							expr: &charClassMatcher{
								pos:        position{line: 94, col: 20, offset: 2602},
								val:        "[a-zA-Z0-9]",
								ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
								ignoreCase: false,
								inverted:   false,
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "FunCall",
			pos:  position{line: 98, col: 1, offset: 2649},
			expr: &actionExpr{
				pos: position{line: 98, col: 12, offset: 2660},
				run: (*parser).callonFunCall1,
				expr: &seqExpr{
					pos: position{line: 98, col: 12, offset: 2660},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 98, col: 12, offset: 2660},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 17, offset: 2665},
								name: "Term",
							},
						},
						&labeledExpr{
							pos:   position{line: 98, col: 22, offset: 2670},
							label: "args",
							expr: &ruleRefExpr{
								pos:  position{line: 98, col: 27, offset: 2675},
								name: "ArgValues",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "ArgValues",
			pos:  position{line: 102, col: 1, offset: 2755},
			expr: &actionExpr{
				pos: position{line: 102, col: 14, offset: 2768},
				run: (*parser).callonArgValues1,
				expr: &seqExpr{
					pos: position{line: 102, col: 14, offset: 2768},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 102, col: 14, offset: 2768},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 102, col: 18, offset: 2772},
							label: "args",
							expr: &zeroOrMoreExpr{
								pos: position{line: 102, col: 23, offset: 2777},
								expr: &ruleRefExpr{
									pos:  position{line: 102, col: 23, offset: 2777},
									name: "KeyValue",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 102, col: 33, offset: 2787},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ArgTypes",
			pos:  position{line: 105, col: 1, offset: 2836},
			expr: &actionExpr{
				pos: position{line: 105, col: 13, offset: 2848},
				run: (*parser).callonArgTypes1,
				expr: &seqExpr{
					pos: position{line: 105, col: 13, offset: 2848},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 105, col: 13, offset: 2848},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 105, col: 17, offset: 2852},
							label: "args",
							expr: &zeroOrMoreExpr{
								pos: position{line: 105, col: 22, offset: 2857},
								expr: &ruleRefExpr{
									pos:  position{line: 105, col: 22, offset: 2857},
									name: "ArgType",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 105, col: 31, offset: 2866},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ArgType",
			pos:  position{line: 108, col: 1, offset: 2912},
			expr: &actionExpr{
				pos: position{line: 108, col: 12, offset: 2923},
				run: (*parser).callonArgType1,
				expr: &seqExpr{
					pos: position{line: 108, col: 12, offset: 2923},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 108, col: 12, offset: 2923},
							label: "slot",
							expr: &choiceExpr{
								pos: position{line: 108, col: 18, offset: 2929},
								alternatives: []any{
									&ruleRefExpr{
										pos:  position{line: 108, col: 18, offset: 2929},
										name: "ArgWithDefault",
									},
									&ruleRefExpr{
										pos:  position{line: 108, col: 35, offset: 2946},
										name: "ArgWithBlockDefault",
									},
									&ruleRefExpr{
										pos:  position{line: 108, col: 57, offset: 2968},
										name: "ArgWithType",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 108, col: 70, offset: 2981},
							expr: &ruleRefExpr{
								pos:  position{line: 108, col: 70, offset: 2981},
								name: "CommaToken",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ArgWithDefault",
			pos:  position{line: 111, col: 1, offset: 3027},
			expr: &actionExpr{
				pos: position{line: 111, col: 19, offset: 3045},
				run: (*parser).callonArgWithDefault1,
				expr: &seqExpr{
					pos: position{line: 111, col: 19, offset: 3045},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 111, col: 19, offset: 3045},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 24, offset: 3050},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 27, offset: 3053},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 29, offset: 3055},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 40, offset: 3066},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 111, col: 42, offset: 3068},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 48, offset: 3074},
								name: "Type",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 53, offset: 3079},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 111, col: 55, offset: 3081},
							val:        "=",
							ignoreCase: false,
							want:       "\"=\"",
						},
						&ruleRefExpr{
							pos:  position{line: 111, col: 59, offset: 3085},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 111, col: 61, offset: 3087},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 111, col: 67, offset: 3093},
								name: "Form",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ArgWithBlockDefault",
			pos:  position{line: 118, col: 1, offset: 3210},
			expr: &actionExpr{
				pos: position{line: 118, col: 24, offset: 3233},
				run: (*parser).callonArgWithBlockDefault1,
				expr: &seqExpr{
					pos: position{line: 118, col: 24, offset: 3233},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 118, col: 24, offset: 3233},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 29, offset: 3238},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 32, offset: 3241},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 34, offset: 3243},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 45, offset: 3254},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 118, col: 47, offset: 3256},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 53, offset: 3262},
								name: "Type",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 118, col: 58, offset: 3267},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 118, col: 60, offset: 3269},
							label: "block",
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 66, offset: 3275},
								name: "Block",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ArgWithType",
			pos:  position{line: 125, col: 1, offset: 3394},
			expr: &actionExpr{
				pos: position{line: 125, col: 16, offset: 3409},
				run: (*parser).callonArgWithType1,
				expr: &seqExpr{
					pos: position{line: 125, col: 16, offset: 3409},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 125, col: 16, offset: 3409},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 21, offset: 3414},
								name: "Id",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 24, offset: 3417},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 26, offset: 3419},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 125, col: 37, offset: 3430},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 125, col: 39, offset: 3432},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 125, col: 45, offset: 3438},
								name: "Type",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "KeyValue",
			pos:  position{line: 132, col: 1, offset: 3531},
			expr: &actionExpr{
				pos: position{line: 132, col: 13, offset: 3543},
				run: (*parser).callonKeyValue1,
				expr: &seqExpr{
					pos: position{line: 132, col: 13, offset: 3543},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 132, col: 13, offset: 3543},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 17, offset: 3547},
								name: "WordToken",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 132, col: 27, offset: 3557},
							name: "ColonToken",
						},
						&ruleRefExpr{
							pos:  position{line: 132, col: 38, offset: 3568},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 132, col: 40, offset: 3570},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 46, offset: 3576},
								name: "Form",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 132, col: 51, offset: 3581},
							expr: &ruleRefExpr{
								pos:  position{line: 132, col: 51, offset: 3581},
								name: "CommaToken",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ColonToken",
			pos:  position{line: 135, col: 1, offset: 3651},
			expr: &litMatcher{
				pos:        position{line: 135, col: 15, offset: 3665},
				val:        ":",
				ignoreCase: false,
				want:       "\":\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Type",
			pos:  position{line: 137, col: 1, offset: 3670},
			expr: &choiceExpr{
				pos: position{line: 137, col: 9, offset: 3678},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 137, col: 9, offset: 3678},
						name: "NonNull",
					},
					&ruleRefExpr{
						pos:  position{line: 137, col: 19, offset: 3688},
						name: "NamedType",
					},
					&ruleRefExpr{
						pos:  position{line: 137, col: 31, offset: 3700},
						name: "ListType",
					},
					&ruleRefExpr{
						pos:  position{line: 137, col: 42, offset: 3711},
						name: "TypeVariable",
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "NamedType",
			pos:  position{line: 138, col: 1, offset: 3724},
			expr: &actionExpr{
				pos: position{line: 138, col: 14, offset: 3737},
				run: (*parser).callonNamedType1,
				expr: &labeledExpr{
					pos:   position{line: 138, col: 14, offset: 3737},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 138, col: 19, offset: 3742},
						name: "UpperId",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "ListType",
			pos:  position{line: 141, col: 1, offset: 3797},
			expr: &actionExpr{
				pos: position{line: 141, col: 13, offset: 3809},
				run: (*parser).callonListType1,
				expr: &seqExpr{
					pos: position{line: 141, col: 13, offset: 3809},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 141, col: 13, offset: 3809},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&labeledExpr{
							pos:   position{line: 141, col: 17, offset: 3813},
							label: "inner",
							expr: &ruleRefExpr{
								pos:  position{line: 141, col: 23, offset: 3819},
								name: "Type",
							},
						},
						&litMatcher{
							pos:        position{line: 141, col: 28, offset: 3824},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "NonNull",
			pos:  position{line: 144, col: 1, offset: 3877},
			expr: &actionExpr{
				pos: position{line: 144, col: 12, offset: 3888},
				run: (*parser).callonNonNull1,
				expr: &seqExpr{
					pos: position{line: 144, col: 12, offset: 3888},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 144, col: 12, offset: 3888},
							label: "inner",
							expr: &ruleRefExpr{
								pos:  position{line: 144, col: 18, offset: 3894},
								name: "Type",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 144, col: 23, offset: 3899},
							name: "BangToken",
						},
					},
				},
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "TypeVariable",
			pos:  position{line: 147, col: 1, offset: 3961},
			expr: &actionExpr{
				pos: position{line: 147, col: 17, offset: 3977},
				run: (*parser).callonTypeVariable1,
				expr: &labeledExpr{
					pos:   position{line: 147, col: 17, offset: 3977},
					label: "v",
					expr: &charClassMatcher{
						pos:        position{line: 147, col: 19, offset: 3979},
						val:        "[a-z]",
						ranges:     []rune{'a', 'z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "BangToken",
			pos:  position{line: 151, col: 1, offset: 4031},
			expr: &litMatcher{
				pos:        position{line: 151, col: 14, offset: 4044},
				val:        "!",
				ignoreCase: false,
				want:       "\"!\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "CommaToken",
			pos:  position{line: 153, col: 1, offset: 4049},
			expr: &seqExpr{
				pos: position{line: 153, col: 15, offset: 4063},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 153, col: 15, offset: 4063},
						name: "_",
					},
					&litMatcher{
						pos:        position{line: 153, col: 17, offset: 4065},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&ruleRefExpr{
						pos:  position{line: 153, col: 21, offset: 4069},
						name: "_",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Infix",
			pos:  position{line: 155, col: 1, offset: 4072},
			expr: &ruleRefExpr{
				pos:  position{line: 155, col: 10, offset: 4081},
				name: "Default",
			},
			leader:        true,
			leftRecursive: true,
		},
		{
			name: "Default",
			pos:  position{line: 156, col: 1, offset: 4089},
			expr: &actionExpr{
				pos: position{line: 156, col: 12, offset: 4100},
				run: (*parser).callonDefault1,
				expr: &seqExpr{
					pos: position{line: 156, col: 12, offset: 4100},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 156, col: 12, offset: 4100},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 156, col: 17, offset: 4105},
								name: "Form",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 156, col: 22, offset: 4110},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 156, col: 24, offset: 4112},
							name: "InterroToken",
						},
						&ruleRefExpr{
							pos:  position{line: 156, col: 37, offset: 4125},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 156, col: 39, offset: 4127},
							label: "right",
							expr: &ruleRefExpr{
								pos:  position{line: 156, col: 45, offset: 4133},
								name: "Term",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "InterroToken",
			pos:  position{line: 159, col: 1, offset: 4191},
			expr: &litMatcher{
				pos:        position{line: 159, col: 17, offset: 4207},
				val:        "?",
				ignoreCase: false,
				want:       "\"?\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Select",
			pos:  position{line: 161, col: 1, offset: 4212},
			expr: &actionExpr{
				pos: position{line: 161, col: 11, offset: 4222},
				run: (*parser).callonSelect1,
				expr: &seqExpr{
					pos: position{line: 161, col: 11, offset: 4222},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 161, col: 11, offset: 4222},
							label: "left",
							expr: &ruleRefExpr{
								pos:  position{line: 161, col: 16, offset: 4227},
								name: "Term",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 21, offset: 4232},
							name: "_",
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 23, offset: 4234},
							name: "DotToken",
						},
						&ruleRefExpr{
							pos:  position{line: 161, col: 32, offset: 4243},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 161, col: 34, offset: 4245},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 161, col: 39, offset: 4250},
								name: "Id",
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: true,
		},
		{
			name: "DotToken",
			pos:  position{line: 164, col: 1, offset: 4306},
			expr: &litMatcher{
				pos:        position{line: 164, col: 13, offset: 4318},
				val:        ".",
				ignoreCase: false,
				want:       "\".\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "List",
			pos:  position{line: 166, col: 1, offset: 4323},
			expr: &actionExpr{
				pos: position{line: 166, col: 9, offset: 4331},
				run: (*parser).callonList1,
				expr: &seqExpr{
					pos: position{line: 166, col: 9, offset: 4331},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 166, col: 9, offset: 4331},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 166, col: 13, offset: 4335},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 166, col: 15, offset: 4337},
							label: "eles",
							expr: &zeroOrMoreExpr{
								pos: position{line: 166, col: 20, offset: 4342},
								expr: &actionExpr{
									pos: position{line: 166, col: 21, offset: 4343},
									run: (*parser).callonList7,
									expr: &seqExpr{
										pos: position{line: 166, col: 21, offset: 4343},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 166, col: 21, offset: 4343},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 166, col: 23, offset: 4345},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 166, col: 25, offset: 4347},
													name: "Form",
												},
											},
											&zeroOrOneExpr{
												pos: position{line: 166, col: 30, offset: 4352},
												expr: &ruleRefExpr{
													pos:  position{line: 166, col: 30, offset: 4352},
													name: "CommaToken",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 166, col: 42, offset: 4364},
												name: "_",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 166, col: 64, offset: 4386},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Block",
			pos:  position{line: 170, col: 1, offset: 4435},
			expr: &actionExpr{
				pos: position{line: 170, col: 10, offset: 4444},
				run: (*parser).callonBlock1,
				expr: &seqExpr{
					pos: position{line: 170, col: 10, offset: 4444},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 170, col: 10, offset: 4444},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 170, col: 14, offset: 4448},
							label: "es",
							expr: &zeroOrMoreExpr{
								pos: position{line: 170, col: 17, offset: 4451},
								expr: &actionExpr{
									pos: position{line: 170, col: 18, offset: 4452},
									run: (*parser).callonBlock6,
									expr: &seqExpr{
										pos: position{line: 170, col: 18, offset: 4452},
										exprs: []any{
											&ruleRefExpr{
												pos:  position{line: 170, col: 18, offset: 4452},
												name: "_",
											},
											&labeledExpr{
												pos:   position{line: 170, col: 20, offset: 4454},
												label: "e",
												expr: &ruleRefExpr{
													pos:  position{line: 170, col: 22, offset: 4456},
													name: "Expr",
												},
											},
											&zeroOrOneExpr{
												pos: position{line: 170, col: 27, offset: 4461},
												expr: &ruleRefExpr{
													pos:  position{line: 170, col: 27, offset: 4461},
													name: "CommaToken",
												},
											},
											&ruleRefExpr{
												pos:  position{line: 170, col: 39, offset: 4473},
												name: "_",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 170, col: 61, offset: 4495},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Symbol",
			pos:  position{line: 176, col: 1, offset: 4594},
			expr: &actionExpr{
				pos: position{line: 176, col: 11, offset: 4604},
				run: (*parser).callonSymbol1,
				expr: &labeledExpr{
					pos:   position{line: 176, col: 11, offset: 4604},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 176, col: 16, offset: 4609},
						name: "Id",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Literal",
			pos:  position{line: 182, col: 1, offset: 4666},
			expr: &choiceExpr{
				pos: position{line: 182, col: 12, offset: 4677},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 182, col: 12, offset: 4677},
						name: "Int",
					},
					&ruleRefExpr{
						pos:  position{line: 182, col: 18, offset: 4683},
						name: "Boolean",
					},
					&ruleRefExpr{
						pos:  position{line: 182, col: 28, offset: 4693},
						name: "String",
					},
					&ruleRefExpr{
						pos:  position{line: 182, col: 37, offset: 4702},
						name: "Quoted",
					},
					&ruleRefExpr{
						pos:  position{line: 182, col: 46, offset: 4711},
						name: "Null",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Int",
			pos:  position{line: 184, col: 1, offset: 4717},
			expr: &choiceExpr{
				pos: position{line: 184, col: 8, offset: 4724},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 184, col: 8, offset: 4724},
						val:        "0",
						ignoreCase: false,
						want:       "\"0\"",
					},
					&actionExpr{
						pos: position{line: 184, col: 14, offset: 4730},
						run: (*parser).callonInt3,
						expr: &seqExpr{
							pos: position{line: 184, col: 14, offset: 4730},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 184, col: 14, offset: 4730},
									name: "NonZeroDecimalDigit",
								},
								&zeroOrMoreExpr{
									pos: position{line: 184, col: 34, offset: 4750},
									expr: &ruleRefExpr{
										pos:  position{line: 184, col: 34, offset: 4750},
										name: "DecimalDigit",
									},
								},
							},
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Exponent",
			pos:  position{line: 192, col: 1, offset: 4893},
			expr: &seqExpr{
				pos: position{line: 192, col: 13, offset: 4905},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 192, col: 13, offset: 4905},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 192, col: 18, offset: 4910},
						expr: &charClassMatcher{
							pos:        position{line: 192, col: 18, offset: 4910},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 192, col: 24, offset: 4916},
						expr: &ruleRefExpr{
							pos:  position{line: 192, col: 24, offset: 4916},
							name: "DecimalDigit",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "String",
			pos:  position{line: 194, col: 1, offset: 4931},
			expr: &actionExpr{
				pos: position{line: 194, col: 11, offset: 4941},
				run: (*parser).callonString1,
				expr: &seqExpr{
					pos: position{line: 194, col: 11, offset: 4941},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 194, col: 11, offset: 4941},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 194, col: 15, offset: 4945},
							expr: &choiceExpr{
								pos: position{line: 194, col: 17, offset: 4947},
								alternatives: []any{
									&seqExpr{
										pos: position{line: 194, col: 17, offset: 4947},
										exprs: []any{
											&notExpr{
												pos: position{line: 194, col: 17, offset: 4947},
												expr: &ruleRefExpr{
													pos:  position{line: 194, col: 18, offset: 4948},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 194, col: 30, offset: 4960,
											},
										},
									},
									&seqExpr{
										pos: position{line: 194, col: 34, offset: 4964},
										exprs: []any{
											&litMatcher{
												pos:        position{line: 194, col: 34, offset: 4964},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 194, col: 39, offset: 4969},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 194, col: 57, offset: 4987},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "EscapedChar",
			pos:  position{line: 203, col: 1, offset: 5178},
			expr: &charClassMatcher{
				pos:        position{line: 203, col: 16, offset: 5193},
				val:        "[\\x00-\\x1f\"\\\\]",
				chars:      []rune{'"', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 205, col: 1, offset: 5209},
			expr: &choiceExpr{
				pos: position{line: 205, col: 19, offset: 5227},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 205, col: 19, offset: 5227},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 205, col: 38, offset: 5246},
						name: "UnicodeEscape",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 207, col: 1, offset: 5261},
			expr: &charClassMatcher{
				pos:        position{line: 207, col: 21, offset: 5281},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 209, col: 1, offset: 5294},
			expr: &seqExpr{
				pos: position{line: 209, col: 18, offset: 5311},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 209, col: 18, offset: 5311},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 209, col: 22, offset: 5315},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 209, col: 31, offset: 5324},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 209, col: 40, offset: 5333},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 209, col: 49, offset: 5342},
						name: "HexDigit",
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 211, col: 1, offset: 5352},
			expr: &charClassMatcher{
				pos:        position{line: 211, col: 17, offset: 5368},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "NonZeroDecimalDigit",
			pos:  position{line: 213, col: 1, offset: 5375},
			expr: &charClassMatcher{
				pos:        position{line: 213, col: 24, offset: 5398},
				val:        "[1-9]",
				ranges:     []rune{'1', '9'},
				ignoreCase: false,
				inverted:   false,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "HexDigit",
			pos:  position{line: 215, col: 1, offset: 5405},
			expr: &charClassMatcher{
				pos:        position{line: 215, col: 13, offset: 5417},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Quoted",
			pos:  position{line: 217, col: 1, offset: 5428},
			expr: &actionExpr{
				pos: position{line: 217, col: 11, offset: 5438},
				run: (*parser).callonQuoted1,
				expr: &seqExpr{
					pos: position{line: 217, col: 11, offset: 5438},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 217, col: 11, offset: 5438},
							val:        "%",
							ignoreCase: false,
							want:       "\"%\"",
						},
						&labeledExpr{
							pos:   position{line: 217, col: 15, offset: 5442},
							label: "quoter",
							expr: &ruleRefExpr{
								pos:  position{line: 217, col: 22, offset: 5449},
								name: "WordToken",
							},
						},
						&litMatcher{
							pos:        position{line: 217, col: 32, offset: 5459},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 217, col: 36, offset: 5463},
							label: "raw",
							expr: &ruleRefExpr{
								pos:  position{line: 217, col: 40, offset: 5467},
								name: "QuotedRawToken",
							},
						},
						&litMatcher{
							pos:        position{line: 217, col: 55, offset: 5482},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "QuotedRawToken",
			pos:  position{line: 223, col: 1, offset: 5555},
			expr: &actionExpr{
				pos: position{line: 223, col: 19, offset: 5573},
				run: (*parser).callonQuotedRawToken1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 223, col: 19, offset: 5573},
					expr: &charClassMatcher{
						pos:        position{line: 223, col: 19, offset: 5573},
						val:        "[^}]",
						chars:      []rune{'}'},
						ignoreCase: false,
						inverted:   true,
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Boolean",
			pos:  position{line: 227, col: 1, offset: 5613},
			expr: &choiceExpr{
				pos: position{line: 227, col: 12, offset: 5624},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 227, col: 12, offset: 5624},
						run: (*parser).callonBoolean2,
						expr: &ruleRefExpr{
							pos:  position{line: 227, col: 12, offset: 5624},
							name: "TrueToken",
						},
					},
					&actionExpr{
						pos: position{line: 228, col: 12, offset: 5675},
						run: (*parser).callonBoolean4,
						expr: &ruleRefExpr{
							pos:  position{line: 228, col: 12, offset: 5675},
							name: "FalseToken",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "TrueToken",
			pos:  position{line: 229, col: 1, offset: 5717},
			expr: &litMatcher{
				pos:        position{line: 229, col: 14, offset: 5730},
				val:        "true",
				ignoreCase: false,
				want:       "\"true\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "FalseToken",
			pos:  position{line: 230, col: 1, offset: 5737},
			expr: &litMatcher{
				pos:        position{line: 230, col: 15, offset: 5751},
				val:        "false",
				ignoreCase: false,
				want:       "\"false\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "Null",
			pos:  position{line: 232, col: 1, offset: 5760},
			expr: &actionExpr{
				pos: position{line: 232, col: 9, offset: 5768},
				run: (*parser).callonNull1,
				expr: &ruleRefExpr{
					pos:  position{line: 232, col: 9, offset: 5768},
					name: "NullToken",
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "NullToken",
			pos:  position{line: 233, col: 1, offset: 5801},
			expr: &litMatcher{
				pos:        position{line: 233, col: 14, offset: 5814},
				val:        "null",
				ignoreCase: false,
				want:       "\"null\"",
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 235, col: 1, offset: 5822},
			expr: &zeroOrMoreExpr{
				pos: position{line: 235, col: 19, offset: 5840},
				expr: &choiceExpr{
					pos: position{line: 235, col: 20, offset: 5841},
					alternatives: []any{
						&charClassMatcher{
							pos:        position{line: 235, col: 20, offset: 5841},
							val:        "[ \\t\\r\\n]",
							chars:      []rune{' ', '\t', '\r', '\n'},
							ignoreCase: false,
							inverted:   false,
						},
						&ruleRefExpr{
							pos:  position{line: 235, col: 32, offset: 5853},
							name: "CommentToken",
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
		{
			name: "CommentToken",
			pos:  position{line: 237, col: 1, offset: 5869},
			expr: &seqExpr{
				pos: position{line: 237, col: 17, offset: 5885},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 237, col: 17, offset: 5885},
						val:        "#",
						ignoreCase: false,
						want:       "\"#\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 237, col: 21, offset: 5889},
						expr: &charClassMatcher{
							pos:        position{line: 237, col: 21, offset: 5889},
							val:        "[^\\n]",
							chars:      []rune{'\n'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
			leader:        false,
			leftRecursive: false,
		},
	},
}

func (c *current) onDash5(e any) (any, error) {
	return e, nil
}

func (p *parser) callonDash5() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDash5(stack["e"])
}

func (c *current) onDash1(es any) (any, error) {
	exprs := sliceOf[Node](es)
	log.Println("!!! DASH", exprs)
	return Block{exprs}, nil
}

func (p *parser) callonDash1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDash1(stack["es"])
}

func (c *current) onClass1(name, block any) (any, error) {
	return ClassDecl{
		Named:      name.(string),
		Value:      block.(Block),
		Visibility: PrivateVisibility, // TODO
	}, nil
}

func (p *parser) callonClass1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClass1(stack["name"], stack["block"])
}

func (c *current) onTypeAndValueSlot1(vis, name, type_, value any) (any, error) {
	return SlotDecl{
		Named:      name.(string),
		Type_:      type_.(TypeNode),
		Value:      value.(Node),
		Visibility: vis.(Visibility),
	}, nil
}

func (p *parser) callonTypeAndValueSlot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAndValueSlot1(stack["vis"], stack["name"], stack["type_"], stack["value"])
}

func (c *current) onValueOnlySlot1(vis, name, val any) (any, error) {
	return SlotDecl{
		Named:      name.(string),
		Value:      val.(Node),
		Visibility: vis.(Visibility),
	}, nil
}

func (p *parser) callonValueOnlySlot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValueOnlySlot1(stack["vis"], stack["name"], stack["val"])
}

func (c *current) onTypeOnlySlot1(vis, name, type_ any) (any, error) {
	return SlotDecl{
		Named:      name.(string),
		Type_:      type_.(TypeNode),
		Visibility: vis.(Visibility),
	}, nil
}

func (p *parser) callonTypeOnlySlot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeOnlySlot1(stack["vis"], stack["name"], stack["type_"])
}

func (c *current) onTypeAndBlockSlot1(vis, name, type_, block any) (any, error) {
	return SlotDecl{
		Named: name.(string),
		Type_: FunTypeNode{nil, type_.(TypeNode)},
		Value: FunDecl{
			Named: name.(string),
			Ret:   type_.(TypeNode),
			Form:  block.(Block),
		},
		Visibility: vis.(Visibility),
	}, nil
}

func (p *parser) callonTypeAndBlockSlot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAndBlockSlot1(stack["vis"], stack["name"], stack["type_"], stack["block"])
}

func (c *current) onTypeAndArgsAndBlockSlot1(vis, name, args, type_, block any) (any, error) {
	return SlotDecl{
		Named: name.(string),
		Type_: FunTypeNode{args.([]SlotDecl), type_.(TypeNode)},
		Value: FunDecl{
			Named: name.(string),
			Args:  args.([]SlotDecl),
			Ret:   type_.(TypeNode),
			Form:  block.(Block),
		},
		Visibility: vis.(Visibility),
	}, nil
}

func (p *parser) callonTypeAndArgsAndBlockSlot1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeAndArgsAndBlockSlot1(stack["vis"], stack["name"], stack["args"], stack["type_"], stack["block"])
}

func (c *current) onVisibility2() (any, error) {
	return PublicVisibility, nil
}

func (p *parser) callonVisibility2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVisibility2()
}

func (c *current) onVisibility4() (any, error) {
	return PrivateVisibility, nil
}

func (p *parser) callonVisibility4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVisibility4()
}

func (c *current) onWordToken1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonWordToken1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onWordToken1()
}

func (c *current) onUpperToken1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonUpperToken1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onUpperToken1()
}

func (c *current) onFunCall1(name, args any) (any, error) {
	return FunCall{name.(Node), Record(args.([]Keyed[Node]))}, nil
}

func (p *parser) callonFunCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunCall1(stack["name"], stack["args"])
}

func (c *current) onArgValues1(args any) (any, error) {
	return sliceOf[Keyed[Node]](args), nil
}

func (p *parser) callonArgValues1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgValues1(stack["args"])
}

func (c *current) onArgTypes1(args any) (any, error) {
	return sliceOf[SlotDecl](args), nil
}

func (p *parser) callonArgTypes1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgTypes1(stack["args"])
}

func (c *current) onArgType1(slot any) (any, error) {
	return slot.(SlotDecl), nil
}

func (p *parser) callonArgType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgType1(stack["slot"])
}

func (c *current) onArgWithDefault1(name, type_, value any) (any, error) {
	return SlotDecl{
		Named: name.(string),
		Type_: type_.(TypeNode),
		Value: value.(Node),
	}, nil
}

func (p *parser) callonArgWithDefault1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgWithDefault1(stack["name"], stack["type_"], stack["value"])
}

func (c *current) onArgWithBlockDefault1(name, type_, block any) (any, error) {
	return SlotDecl{
		Named: name.(string),
		Type_: type_.(TypeNode),
		Value: block.(Block),
	}, nil
}

func (p *parser) callonArgWithBlockDefault1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgWithBlockDefault1(stack["name"], stack["type_"], stack["block"])
}

func (c *current) onArgWithType1(name, type_ any) (any, error) {
	return SlotDecl{
		Named: name.(string),
		Type_: type_.(TypeNode),
	}, nil
}

func (p *parser) callonArgWithType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgWithType1(stack["name"], stack["type_"])
}

func (c *current) onKeyValue1(key, value any) (any, error) {
	return Keyed[Node]{key.(string), value.(Node)}, nil
}

func (p *parser) callonKeyValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyValue1(stack["key"], stack["value"])
}

func (c *current) onNamedType1(name any) (any, error) {
	return NamedTypeNode{name.(string)}, nil
}

func (p *parser) callonNamedType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNamedType1(stack["name"])
}

func (c *current) onListType1(inner any) (any, error) {
	return ListTypeNode{inner.(TypeNode)}, nil
}

func (p *parser) callonListType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onListType1(stack["inner"])
}

func (c *current) onNonNull1(inner any) (any, error) {
	return NonNullTypeNode{inner.(TypeNode)}, nil
}

func (p *parser) callonNonNull1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNonNull1(stack["inner"])
}

func (c *current) onTypeVariable1(v any) (any, error) {
	return VariableTypeNode{v.(byte)}, nil
}

func (p *parser) callonTypeVariable1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTypeVariable1(stack["v"])
}

func (c *current) onDefault1(left, right any) (any, error) {
	return Default{left.(Node), right.(Node)}, nil
}

func (p *parser) callonDefault1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDefault1(stack["left"], stack["right"])
}

func (c *current) onSelect1(left, name any) (any, error) {
	return Select{left.(Node), name.(string)}, nil
}

func (p *parser) callonSelect1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSelect1(stack["left"], stack["name"])
}

func (c *current) onList7(e any) (any, error) {
	return e, nil
}

func (p *parser) callonList7() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList7(stack["e"])
}

func (c *current) onList1(eles any) (any, error) {
	return List{sliceOf[Node](eles)}, nil
}

func (p *parser) callonList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList1(stack["eles"])
}

func (c *current) onBlock6(e any) (any, error) {
	return e, nil
}

func (p *parser) callonBlock6() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBlock6(stack["e"])
}

func (c *current) onBlock1(es any) (any, error) {
	exprs := sliceOf[Node](es)
	log.Println("!!! BLOCK", exprs)
	return Block{exprs}, nil
}

func (p *parser) callonBlock1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBlock1(stack["es"])
}

func (c *current) onSymbol1(name any) (any, error) {
	return Symbol{name.(string)}, nil
}

func (p *parser) callonSymbol1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol1(stack["name"])
}

func (c *current) onInt3() (any, error) {
	value, err := strconv.ParseInt(string(c.text), 10, 64)
	if err != nil {
		return nil, err
	}
	return Int(value), nil
}

func (p *parser) callonInt3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInt3()
}

func (c *current) onString1() (any, error) {
	c.text = bytes.Replace(c.text, []byte(`\/`), []byte(`/`), -1)
	value, err := strconv.Unquote(string(c.text))
	if err != nil {
		return nil, err
	}
	return String{value}, nil
}

func (p *parser) callonString1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onString1()
}

func (c *current) onQuoted1(quoter, raw any) (any, error) {
	return Quoted{
		quoter.(string),
		raw.(string),
	}, nil
}

func (p *parser) callonQuoted1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuoted1(stack["quoter"], stack["raw"])
}

func (c *current) onQuotedRawToken1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonQuotedRawToken1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onQuotedRawToken1()
}

func (c *current) onBoolean2() (any, error) {
	return Boolean(true), nil
}

func (p *parser) callonBoolean2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean2()
}

func (c *current) onBoolean4() (any, error) {
	return Boolean(false), nil
}

func (p *parser) callonBoolean4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBoolean4()
}

func (c *current) onNull1() (any, error) {
	return Null{}, nil
}

func (p *parser) callonNull1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any

	leader        bool
	leftRecursive bool
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type ruleWithExpsStack struct {
	rule   *rule
	estack []any
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleRecursiveLeader(rule *rule) (any, bool) {
	result, ok := p.getMemoized(rule)
	if ok {
		p.restore(result.end)
		return result.v, result.b
	}

	if p.debug {
		defer p.out(p.in("recursive " + rule.name))
	}

	var (
		depth      = 0
		startMark  = p.pt
		lastResult = resultTuple{nil, false, startMark}
		lastErrors = *p.errs
	)

	for {
		lastState := p.cloneState()
		p.setMemoized(startMark, rule, lastResult)
		val, ok := p.parseRule(rule)
		endMark := p.pt
		if p.debug {
			p.printIndent("RECURSIVE", fmt.Sprintf(
				"Rule %s depth %d: %t -> %s",
				rule.name, depth, ok, string(p.sliceFrom(startMark))))
		}
		if (!ok) || (endMark.offset <= lastResult.end.offset && depth != 0) {
			p.restoreState(lastState)
			*p.errs = lastErrors
			break
		}
		lastResult = resultTuple{val, ok, endMark}
		lastErrors = *p.errs
		p.restore(startMark)
		depth++
	}

	p.restore(lastResult.end)
	p.setMemoized(startMark, rule, lastResult)
	return lastResult.v, lastResult.b
}

func (p *parser) parseRuleRecursiveNoLeader(rule *rule) (any, bool) {
	return p.parseRule(rule)
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize || rule.leftRecursive {
		if rule.leader {
			val, ok = p.parseRuleRecursiveLeader(rule)
		} else if p.memoize && !rule.leftRecursive {
			val, ok = p.parseRuleMemoize(rule)
		} else {
			val, ok = p.parseRuleRecursiveNoLeader(rule)
		}
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	isLeftRecusion := p.rstack[len(p.rstack)-1].leftRecursive
	if p.memoize && !isLeftRecusion {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize && !isLeftRecusion {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
