// Code generated by pigeon; DO NOT EDIT.

package ast

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

func sliceOf[T any](val any) []T {
	anys := val.([]any)
	ts := make([]T, len(anys))
	for i, node := range anys {
		ts[i] = node.(T)
	}
	return ts
}

var g = &grammar{
	rules: []*rule{
		{
			name: "Dash",
			pos:  position{line: 16, col: 1, offset: 211},
			expr: &actionExpr{
				pos: position{line: 16, col: 9, offset: 219},
				run: (*parser).callonDash1,
				expr: &seqExpr{
					pos: position{line: 16, col: 9, offset: 219},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 16, col: 9, offset: 219},
							label: "nodes",
							expr: &zeroOrMoreExpr{
								pos: position{line: 16, col: 15, offset: 225},
								expr: &ruleRefExpr{
									pos:  position{line: 16, col: 15, offset: 225},
									name: "Form",
								},
							},
						},
						&notExpr{
							pos: position{line: 16, col: 21, offset: 231},
							expr: &anyMatcher{
								line: 16, col: 22, offset: 232,
							},
						},
					},
				},
			},
		},
		{
			name: "Form",
			pos:  position{line: 20, col: 1, offset: 274},
			expr: &actionExpr{
				pos: position{line: 20, col: 9, offset: 282},
				run: (*parser).callonForm1,
				expr: &labeledExpr{
					pos:   position{line: 20, col: 9, offset: 282},
					label: "node",
					expr: &choiceExpr{
						pos: position{line: 20, col: 15, offset: 288},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 20, col: 15, offset: 288},
								name: "Call",
							},
							&ruleRefExpr{
								pos:  position{line: 20, col: 22, offset: 295},
								name: "Infix",
							},
							&ruleRefExpr{
								pos:  position{line: 20, col: 30, offset: 303},
								name: "List",
							},
							&ruleRefExpr{
								pos:  position{line: 20, col: 37, offset: 310},
								name: "Literal",
							},
							&ruleRefExpr{
								pos:  position{line: 20, col: 47, offset: 320},
								name: "FunDecl",
							},
							&ruleRefExpr{
								pos:  position{line: 20, col: 57, offset: 330},
								name: "ClsDecl",
							},
							&ruleRefExpr{
								pos:  position{line: 20, col: 67, offset: 340},
								name: "Symbol",
							},
						},
					},
				},
			},
		},
		{
			name: "Id",
			pos:  position{line: 24, col: 1, offset: 372},
			expr: &actionExpr{
				pos: position{line: 24, col: 7, offset: 378},
				run: (*parser).callonId1,
				expr: &labeledExpr{
					pos:   position{line: 24, col: 7, offset: 378},
					label: "name",
					expr: &oneOrMoreExpr{
						pos: position{line: 24, col: 12, offset: 383},
						expr: &charClassMatcher{
							pos:        position{line: 24, col: 12, offset: 383},
							val:        "[a-zA-Z0-9]",
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Call",
			pos:  position{line: 26, col: 1, offset: 418},
			expr: &actionExpr{
				pos: position{line: 26, col: 9, offset: 426},
				run: (*parser).callonCall1,
				expr: &seqExpr{
					pos: position{line: 26, col: 9, offset: 426},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 26, col: 9, offset: 426},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 26, col: 14, offset: 431},
								name: "Id",
							},
						},
						&litMatcher{
							pos:        position{line: 26, col: 17, offset: 434},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 26, col: 21, offset: 438},
							label: "params",
							expr: &zeroOrMoreExpr{
								pos: position{line: 26, col: 28, offset: 445},
								expr: &ruleRefExpr{
									pos:  position{line: 26, col: 28, offset: 445},
									name: "KeyValue",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 26, col: 38, offset: 455},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "KeyValue",
			pos:  position{line: 30, col: 1, offset: 529},
			expr: &actionExpr{
				pos: position{line: 30, col: 13, offset: 541},
				run: (*parser).callonKeyValue1,
				expr: &seqExpr{
					pos: position{line: 30, col: 13, offset: 541},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 30, col: 13, offset: 541},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 17, offset: 545},
								name: "Id",
							},
						},
						&litMatcher{
							pos:        position{line: 30, col: 20, offset: 548},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&labeledExpr{
							pos:   position{line: 30, col: 24, offset: 552},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 30, offset: 558},
								name: "Form",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 30, col: 35, offset: 563},
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 35, offset: 563},
								name: "Comma",
							},
						},
					},
				},
			},
		},
		{
			name: "KeyType",
			pos:  position{line: 34, col: 1, offset: 623},
			expr: &actionExpr{
				pos: position{line: 34, col: 12, offset: 634},
				run: (*parser).callonKeyType1,
				expr: &seqExpr{
					pos: position{line: 34, col: 12, offset: 634},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 34, col: 12, offset: 634},
							label: "key",
							expr: &ruleRefExpr{
								pos:  position{line: 34, col: 16, offset: 638},
								name: "Id",
							},
						},
						&litMatcher{
							pos:        position{line: 34, col: 19, offset: 641},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&labeledExpr{
							pos:   position{line: 34, col: 23, offset: 645},
							label: "type_",
							expr: &ruleRefExpr{
								pos:  position{line: 34, col: 29, offset: 651},
								name: "Type",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 34, col: 34, offset: 656},
							expr: &ruleRefExpr{
								pos:  position{line: 34, col: 34, offset: 656},
								name: "Comma",
							},
						},
					},
				},
			},
		},
		{
			name: "Comma",
			pos:  position{line: 38, col: 1, offset: 723},
			expr: &litMatcher{
				pos:        position{line: 38, col: 10, offset: 732},
				val:        ",",
				ignoreCase: false,
				want:       "\",\"",
			},
		},
		{
			name: "Infix",
			pos:  position{line: 40, col: 1, offset: 737},
			expr: &notExpr{
				pos: position{line: 40, col: 10, offset: 746},
				expr: &anyMatcher{
					line: 40, col: 11, offset: 747,
				},
			},
		},
		{
			name: "FunDecl",
			pos:  position{line: 42, col: 1, offset: 758},
			expr: &actionExpr{
				pos: position{line: 42, col: 12, offset: 769},
				run: (*parser).callonFunDecl1,
				expr: &seqExpr{
					pos: position{line: 42, col: 12, offset: 769},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 42, col: 12, offset: 769},
							val:        "fun",
							ignoreCase: false,
							want:       "\"fun\"",
						},
						&labeledExpr{
							pos:   position{line: 42, col: 18, offset: 775},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 23, offset: 780},
								name: "Id",
							},
						},
						&labeledExpr{
							pos:   position{line: 42, col: 26, offset: 783},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 42, col: 31, offset: 788},
								expr: &ruleRefExpr{
									pos:  position{line: 42, col: 31, offset: 788},
									name: "ArgTypes",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 42, col: 41, offset: 798},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&labeledExpr{
							pos:   position{line: 42, col: 45, offset: 802},
							label: "ret",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 49, offset: 806},
								name: "Type",
							},
						},
						&labeledExpr{
							pos:   position{line: 42, col: 54, offset: 811},
							label: "body",
							expr: &ruleRefExpr{
								pos:  position{line: 42, col: 59, offset: 816},
								name: "Block",
							},
						},
					},
				},
			},
		},
		{
			name: "ArgTypes",
			pos:  position{line: 51, col: 1, offset: 940},
			expr: &actionExpr{
				pos: position{line: 51, col: 13, offset: 952},
				run: (*parser).callonArgTypes1,
				expr: &seqExpr{
					pos: position{line: 51, col: 13, offset: 952},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 51, col: 13, offset: 952},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 51, col: 17, offset: 956},
							label: "args",
							expr: &zeroOrMoreExpr{
								pos: position{line: 51, col: 22, offset: 961},
								expr: &ruleRefExpr{
									pos:  position{line: 51, col: 22, offset: 961},
									name: "KeyType",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 51, col: 31, offset: 970},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "ArgValues",
			pos:  position{line: 55, col: 1, offset: 1020},
			expr: &actionExpr{
				pos: position{line: 55, col: 14, offset: 1033},
				run: (*parser).callonArgValues1,
				expr: &seqExpr{
					pos: position{line: 55, col: 14, offset: 1033},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 55, col: 14, offset: 1033},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&labeledExpr{
							pos:   position{line: 55, col: 18, offset: 1037},
							label: "args",
							expr: &zeroOrMoreExpr{
								pos: position{line: 55, col: 23, offset: 1042},
								expr: &ruleRefExpr{
									pos:  position{line: 55, col: 23, offset: 1042},
									name: "KeyValue",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 55, col: 33, offset: 1052},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "ClsDecl",
			pos:  position{line: 59, col: 1, offset: 1102},
			expr: &actionExpr{
				pos: position{line: 59, col: 12, offset: 1113},
				run: (*parser).callonClsDecl1,
				expr: &seqExpr{
					pos: position{line: 59, col: 12, offset: 1113},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 59, col: 12, offset: 1113},
							val:        "cls",
							ignoreCase: false,
							want:       "\"cls\"",
						},
						&labeledExpr{
							pos:   position{line: 59, col: 18, offset: 1119},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 59, col: 23, offset: 1124},
								name: "Id",
							},
						},
						&litMatcher{
							pos:        position{line: 59, col: 26, offset: 1127},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 59, col: 30, offset: 1131},
							label: "body",
							expr: &zeroOrMoreExpr{
								pos: position{line: 59, col: 35, offset: 1136},
								expr: &ruleRefExpr{
									pos:  position{line: 59, col: 35, offset: 1136},
									name: "SlotDecl",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 59, col: 45, offset: 1146},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "SlotDecl",
			pos:  position{line: 63, col: 1, offset: 1220},
			expr: &actionExpr{
				pos: position{line: 63, col: 13, offset: 1232},
				run: (*parser).callonSlotDecl1,
				expr: &seqExpr{
					pos: position{line: 63, col: 13, offset: 1232},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 63, col: 13, offset: 1232},
							label: "vis",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 17, offset: 1236},
								name: "Visibility",
							},
						},
						&labeledExpr{
							pos:   position{line: 63, col: 28, offset: 1247},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 33, offset: 1252},
								name: "Id",
							},
						},
						&labeledExpr{
							pos:   position{line: 63, col: 36, offset: 1255},
							label: "args",
							expr: &zeroOrOneExpr{
								pos: position{line: 63, col: 41, offset: 1260},
								expr: &ruleRefExpr{
									pos:  position{line: 63, col: 41, offset: 1260},
									name: "ArgTypes",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 63, col: 51, offset: 1270},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&labeledExpr{
							pos:   position{line: 63, col: 55, offset: 1274},
							label: "ret",
							expr: &ruleRefExpr{
								pos:  position{line: 63, col: 59, offset: 1278},
								name: "Type",
							},
						},
						&labeledExpr{
							pos:   position{line: 63, col: 64, offset: 1283},
							label: "body",
							expr: &zeroOrOneExpr{
								pos: position{line: 63, col: 69, offset: 1288},
								expr: &ruleRefExpr{
									pos:  position{line: 63, col: 69, offset: 1288},
									name: "Block",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Visibility",
			pos:  position{line: 73, col: 1, offset: 1436},
			expr: &choiceExpr{
				pos: position{line: 73, col: 15, offset: 1450},
				alternatives: []any{
					&actionExpr{
						pos: position{line: 73, col: 15, offset: 1450},
						run: (*parser).callonVisibility2,
						expr: &litMatcher{
							pos:        position{line: 73, col: 15, offset: 1450},
							val:        "pub",
							ignoreCase: false,
							want:       "\"pub\"",
						},
					},
					&actionExpr{
						pos: position{line: 74, col: 15, offset: 1503},
						run: (*parser).callonVisibility4,
						expr: &litMatcher{
							pos:        position{line: 74, col: 15, offset: 1503},
							val:        "pri",
							ignoreCase: false,
							want:       "\"pri\"",
						},
					},
				},
			},
		},
		{
			name: "Literal",
			pos:  position{line: 76, col: 1, offset: 1544},
			expr: &notExpr{
				pos: position{line: 76, col: 12, offset: 1555},
				expr: &anyMatcher{
					line: 76, col: 13, offset: 1556,
				},
			},
		},
		{
			name: "Symbol",
			pos:  position{line: 78, col: 1, offset: 1567},
			expr: &actionExpr{
				pos: position{line: 78, col: 11, offset: 1577},
				run: (*parser).callonSymbol1,
				expr: &labeledExpr{
					pos:   position{line: 78, col: 11, offset: 1577},
					label: "name",
					expr: &ruleRefExpr{
						pos:  position{line: 78, col: 16, offset: 1582},
						name: "Id",
					},
				},
			},
		},
		{
			name: "List",
			pos:  position{line: 82, col: 1, offset: 1627},
			expr: &actionExpr{
				pos: position{line: 82, col: 9, offset: 1635},
				run: (*parser).callonList1,
				expr: &seqExpr{
					pos: position{line: 82, col: 9, offset: 1635},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 82, col: 9, offset: 1635},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&labeledExpr{
							pos:   position{line: 82, col: 13, offset: 1639},
							label: "eles",
							expr: &zeroOrMoreExpr{
								pos: position{line: 82, col: 18, offset: 1644},
								expr: &ruleRefExpr{
									pos:  position{line: 82, col: 18, offset: 1644},
									name: "Form",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 82, col: 24, offset: 1650},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Block",
			pos:  position{line: 86, col: 1, offset: 1700},
			expr: &actionExpr{
				pos: position{line: 86, col: 10, offset: 1709},
				run: (*parser).callonBlock1,
				expr: &seqExpr{
					pos: position{line: 86, col: 10, offset: 1709},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 86, col: 10, offset: 1709},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&labeledExpr{
							pos:   position{line: 86, col: 14, offset: 1713},
							label: "body",
							expr: &zeroOrMoreExpr{
								pos: position{line: 86, col: 19, offset: 1718},
								expr: &ruleRefExpr{
									pos:  position{line: 86, col: 19, offset: 1718},
									name: "Form",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 86, col: 25, offset: 1724},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
	},
}

func (c *current) onDash1(nodes any) (any, error) {
	return sliceOf[Node](nodes), nil
}

func (p *parser) callonDash1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDash1(stack["nodes"])
}

func (c *current) onForm1(node any) (any, error) {
	return node, nil
}

func (p *parser) callonForm1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onForm1(stack["node"])
}

func (c *current) onId1(name any) (any, error) {
	return name, nil
}

func (p *parser) callonId1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onId1(stack["name"])
}

func (c *current) onCall1(name, params any) (any, error) {
	return &Call{name.(string), sliceOf[Keyed[Node]](params)}, nil
}

func (p *parser) callonCall1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCall1(stack["name"], stack["params"])
}

func (c *current) onKeyValue1(key, value any) (any, error) {
	return &Keyed[Node]{key.(string), value}, nil
}

func (p *parser) callonKeyValue1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyValue1(stack["key"], stack["value"])
}

func (c *current) onKeyType1(key, type_ any) (any, error) {
	return &Keyed[Type]{key.(string), type_.(Type)}, nil
}

func (p *parser) callonKeyType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onKeyType1(stack["key"], stack["type_"])
}

func (c *current) onFunDecl1(name, args, ret, body any) (any, error) {
	return &FunDecl{
		name.(string),
		sliceOf[Keyed[Type]](args),
		ret.(Type),
		body.(Block),
	}, nil
}

func (p *parser) callonFunDecl1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunDecl1(stack["name"], stack["args"], stack["ret"], stack["body"])
}

func (c *current) onArgTypes1(args any) (any, error) {
	return sliceOf[Keyed[Type]](args), nil
}

func (p *parser) callonArgTypes1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgTypes1(stack["args"])
}

func (c *current) onArgValues1(args any) (any, error) {
	return sliceOf[Keyed[Node]](args), nil
}

func (p *parser) callonArgValues1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArgValues1(stack["args"])
}

func (c *current) onClsDecl1(name, body any) (any, error) {
	return &ClassDecl{name.(string), sliceOf[SlotDecl](body)}, nil
}

func (p *parser) callonClsDecl1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onClsDecl1(stack["name"], stack["body"])
}

func (c *current) onSlotDecl1(vis, name, args, ret, body any) (any, error) {
	return &SlotDecl{
		name.(string),
		sliceOf[Keyed[Type]](args),
		ret.(Type),
		vis.(Visibility),
		body.(Block),
	}, nil
}

func (p *parser) callonSlotDecl1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSlotDecl1(stack["vis"], stack["name"], stack["args"], stack["ret"], stack["body"])
}

func (c *current) onVisibility2() (any, error) {
	return PublicVisibility, nil
}

func (p *parser) callonVisibility2() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVisibility2()
}

func (c *current) onVisibility4() (any, error) {
	return PrivateVisibility, nil
}

func (p *parser) callonVisibility4() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onVisibility4()
}

func (c *current) onSymbol1(name any) (any, error) {
	return &Symbol{name.(string)}, nil
}

func (p *parser) callonSymbol1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSymbol1(stack["name"])
}

func (c *current) onList1(eles any) (any, error) {
	return &List{sliceOf[Node](eles)}, nil
}

func (p *parser) callonList1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onList1(stack["eles"])
}

func (c *current) onBlock1(body any) (any, error) {
	return &Block{sliceOf[Node](body)}, nil
}

func (p *parser) callonBlock1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBlock1(stack["body"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
